Repository yuki-snow1823/diary, pull requests merged in 2023-12, with the labels that each got.

#116 【仮実装】user一覧の画面について奈良さんのjournal一覧の実装を丸ぱくりしたPR
  frontend/src/App.tsx
  frontend/src/user/graphql/query.ts
  frontend/src/user/index/component/IndexUserContainer.tsx
  frontend/src/user/index/component/IndexUserPresentational.tsx
Labels: フロントエンド, GraphQL

#114 jouranl index pageの作成
  frontend/src/App.tsx
  frontend/src/journal/index/component/IndexJournalContainer.tsx
  frontend/src/journal/index/component/IndexJournalPresentational.tsx
  frontend/src/journal/index/graphql/query.ts
Labels: フロントエンド

#131 herokuからrenderに移行する
  backend/Dockerfile
  backend/Gemfile
  backend/Gemfile.lock
  backend/bin/render-build.sh
  backend/config/credentials.yml.enc
  backend/config/database.yml
  frontend/src/journal/index/component/IndexJournalPresentational.tsx
  frontend/src/user/index/component/IndexUserPresentational.tsx
Labels: レビュー待ち

#126 ユーザーの詳細ページを作る
  backend/Gemfile
  frontend/src/App.tsx
  frontend/src/sign_in/hooks/SiginInHooks.ts
  frontend/src/sign_up/hooks/SignUpHooks.ts
  frontend/src/user/show/component/ShowUserContainer.tsx
  frontend/src/user/show/component/ShowUserPresentational.tsx
  frontend/src/user/show/graphql/query.ts
  frontend/src/user/show/hooks/ShowUserHooks.tsx
Labels: フロントエンド
