Repository yuki-snow1823/diary, pull requests merged in 2023-07, with the labels that each got.

#62 create_journalにrequieredの記述を追加
  backend/app/graphql/mutations/create_journal.rb
Labels: レビュー完了

#63 ログイン画面と機能を作成しました
  frontend/package.json
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/lib/api/auth.ts
  frontend/src/lib/api/client.ts
  frontend/src/sign_in/component/SignInContainer.tsx
  frontend/src/sign_in/component/SignInPresentational.tsx
  frontend/src/sign_in/hooks/SiginInHooks.tsx
  frontend/yarn.lock
Labels: フロントエンド, レビュー待ち

#77 yarnをdockerコンテナではなくホストマシン上で実行するようにした
  README.md
  docker-compose.yml
  frontend/package.json
Labels: 環境構築, フロントエンド, レビュー待ち

#78 wait-for-itを初回の起動時だけ実行する
  backend/Dockerfile
  backend/Dockerfile.dev
Labels: バグ, 環境構築, レビュー待ち

#73 mutations_rspec実装(execute方式)
  backend/app/graphql/mutations/update_journal.rb
  backend/spec/graphql/mutations/create_journal_spec.rb
  backend/spec/graphql/mutations/delete_journal_spec.rb
  backend/spec/graphql/mutations/update_journal_spec.rb
Labels: GraphQL

#83 トップページにログインフォームを表示させました
  frontend/src/App.tsx
  frontend/src/sign_in/component/SiginInPresentational.test.tsx
  frontend/src/sign_in/component/SignInPresentational.tsx
Labels: フロントエンド, レビュー待ち

#87 プルリクのテンプレートを追加
  .github/pull_request_template.md
Labels: レビュー待ち

#86 wikiへのリンクとテスト実行方法をReadmeに追記
  README.md
Labels: 環境構築, レビュー待ち

#85 いらないファイルを消しました
  backend/test/channels/application_cable/connection_test.rb
  backend/test/controllers/.keep
  backend/test/fixtures/files/.keep
  backend/test/fixtures/journals.yml
  backend/test/integration/.keep
  backend/test/mailers/.keep
  backend/test/models/.keep
  backend/test/models/journal_test.rb
  backend/test/test_helper.rb
  frontend/src/Sample.tsx
  frontend/src/Test.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/logo.svg
  frontend/src/reportWebVitals.ts
Labels: 環境構築, レビュー待ち

#92 Reactのimportのbaseはsrcにした
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/sign_in/hooks/SiginInHooks.ts
  frontend/tsconfig.json
Labels: 環境構築, フロントエンド, レビュー待ち

#90 ついにJournalがUserID付きで新規投稿できるようになる
  backend/app/graphql/mutations/create_journal.rb
  frontend/src/App.tsx
  frontend/src/journal/new/component/JournalNewContainer.tsx
  frontend/src/journal/new/component/JournalNewPresentational.tsx
  frontend/src/journal/new/graphql/mutation.ts
  frontend/src/journal/new/hooks/JournalNewHooks.ts
Labels: フロントエンド, GraphQL, レビュー待ち

#84 Rubocopの設定を追加+引数の改行を防止
  backend/.rubocop.yml
  backend/app/graphql/mutations/create_journal.rb
  backend/app/graphql/mutations/delete_journal.rb
Labels: バックエンド, レビュー待ち

#101 トップページの変更とyarnなどが入っていない方向けの記述追加
  README.md
  frontend/src/App.css
  frontend/src/App.tsx
Labels: フロントエンド, レビュー待ち
