Repository yuki-snow1823/diary, pull requests merged in 2023-09, with the labels that each got.

#125 NotoSansJPの導入
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/sign_in/component/SignInPresentational.tsx
Labels: フロントエンド, レビュー待ち

#113 query_type_specで取得できるJournalの値が期待通りかを検証するようにした
  backend/app/graphql/types/query_type.rb
  backend/spec/graphql/types/query_type_spec.rb
Labels: バックエンド, レビュー待ち

#115 userの一覧を取得するクエリを作成
  backend/app/graphql/types/query_type.rb
  backend/spec/graphql/types/query_type_spec.rb
Labels: フロントエンド, GraphQL
